### ISSUE TITLE
Unable to install.

### ISSUE THREAD

**Issue by woutershep** [kusumi/fileobj#2]
Hi, i tried to use this piece of software but i was unable to install it.

It seems that installing it depends on it beeing installed already (and as a result this means setup.py will probably be using the wrong information out of the already installed version)

> $ python2.7 -B setup.py config
> running config
> Traceback (most recent call last):
>   File "setup.py", line 30, in <module>
>     import fileobj.package
> ImportError: No module named fileobj.package

I tried to work around this with PYTHONPATH, which made it got a little but further, but not much

> $ PYTHONPATH=`pwd`/src python2.7 -B setup.py config
> running config
> Traceback (most recent call last):
>   File "setup.py", line 30, in <module>
>     import fileobj.package
>   File "/var/tmp/paludis/build/app-editors-fileobj-0.7.23/work/PYTHON_ABIS/2.7/fileobj-0.7.23/src/fileobj.py", line 27, in <module>
>     from . import fileattr
> ValueError: Attempted relative import in non-package

**Comment by kusumi** [comment]
do what's written here
https://github.com/kusumi/fileobj#install

**Comment by woutershep** [comment]
That works however that doesn't quite address the issue. Maybe some more background will help you see the bigger picture: I want to package it for a linux distribution, which conveniently comes with a standard way to install setup.py (setuptools/distutils) packages.

It splits it up in three parts. First as a 'regular' user it runs 'config' (think ./configure), then a 'build' (think make). Then finally an 'install' as the root user (think sudo make install). Perhaps using the config wasn't the best example in the world but it was the first step and thus the first to report an error.

If we just skipped the config phase it still wouldn't work though.
When doing just the build step it also failed:
$ python2.7 -B setup.py build
running build
running build_py
creating build
creating build/lib
creating build/lib/fileobj
copying src/__init__.py -> build/lib/fileobj
...snip...
copying src/ext/usbdev.py -> build/lib/fileobj/ext
warning: build_py: byte-compiling is disabled, skipping.

running build_scripts
creating build/scripts-2.7
copying and adjusting script/fileobj -> build/scripts-2.7
changing mode of build/scripts-2.7/fileobj from 644 to 755
Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    import fileobj.package
ImportError: No module named fileobj.package

Seeing as how you advertised "See Installing Python Modules for custom installation" i expected that i could install this package using the steps actually described by that link:
https://docs.python.org/2/install/#splitting-the-job-up

The only reason the install in that page works is because it installs it to the system during the execution of setup.py, and then when it reaches the import statement this installing has been done and it picks it up from the system. However - If i where to install it to a custom location (which i also am, because i want to put the files into a package, not the main system) with --root=/tmp/fileobj for example, then the install fails because when it reaches the import there is no fileobj files in the system, they are in /tmp/fileobj instead where it isnt looking.

(sticking as close to your command as i can, note the added --root)
% python2.7 ./setup.py install --force --record ./install.out --root=/tmp/fileobj
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/fileobj
copying src/__init__.py -> build/lib/fileobj
...snip...
copying src/ext/usbdev.py -> build/lib/fileobj/ext
running build_scripts
creating build/scripts-2.7
copying and adjusting script/fileobj -> build/scripts-2.7
changing mode of build/scripts-2.7/fileobj from 644 to 755
running install_lib
creating /tmp/fileobj
...snip...
byte-compiling /tmp/fileobj/usr/x86_64-pc-linux-gnu/lib/python2.7/site-packages/fileobj/ext/usbdev.py to usbdev.pyc
running install_scripts
creating /tmp/fileobj/usr/x86_64-pc-linux-gnu/bin
copying build/scripts-2.7/fileobj -> /tmp/fileobj/usr/x86_64-pc-linux-gnu/bin
changing mode of /tmp/fileobj/usr/x86_64-pc-linux-gnu/bin/fileobj to 755
running install_egg_info
Writing /tmp/fileobj/usr/x86_64-pc-linux-gnu/lib/python2.7/site-packages/fileobj-v0.7.23-py2.7.egg-info
writing list of installed files to './install.out'
Traceback (most recent call last):
  File "./setup.py", line 30, in <module>
    import fileobj.package
ImportError: No module named fileobj.package

So currently the only use case the setup.py is allowing is 'install directly to system'.
It doesn't support 'build, then install' nor does it support 'install to custom location'.
Installing to a custom location is absolutely mandatory for me to package this software.

I hope this makes the issue more clear.

**Comment by kusumi** [comment]
OK, feel free to either fork this or send me a patch or pull request. I don't use setup.py options other than install, clean, and sdist, however if the setup.py is losing generality because of its implementation, I'm willing to take patches.

Line 30+ of setup.py could be removed if that's the only thing bothering you. I've seen some issues on runtime (not setup.py runtime but the application runtime) when some older version was already installed and certain files have been renamed in the newly installed version, so I've added some manual test code in line 30+, which wasn't really a clean piece of code in the first place. Things have been stable in the last 1-2 years with a few file renames, so this test code is no longer that important. If that's gone, setup.py only depends on builtin modules and a local directory src/.

Things I don't want to do in setup.py (and src/*) are

1. Be Linux specific. This program is intended to be portable among unix like OS (currently Linux and BSDs are supported and maybe MacOS in the future), if not Windows, so setup.py or whatever invoked via setup.py must not be Linux specific.

2. Have dependencies on external modules that aren't builtin unless there is a strong reason to do so.

3. Have dependencies on certain Python version (and above) that breaks on any of the currently supported Python versions.

4. Change behavior of plain "python ./setup.py install". Removing --force option from README is okay if things work without --force when some older version is installed.

Other than that I really don't care too much about setup.py.

**Comment by woutershep** [comment]
How about instead of removing we do https://github.com/kusumi/fileobj/pull/3 - this way you can keep the logic for helping debug problems but it wont be getting in the way of setup.py stuff.

**Comment by kusumi** [comment]
Thanks.
https://github.com/kusumi/fileobj/commit/9e2bc6a857bee0a031bec4bd093068335613b8a6

**Comment by woutershep** [comment]
Works great, marking this as fixed. :)
